mkdir -p /vendorapp
mkdir -p /vendoretc
mkdir -p /vendoretc/seccomp_policy
mkdir -p /vendoretc/lm
mkdir -p /vendoretc/lm/prekill
mkdir -p /vendoretc/vintf
mkdir -p /vendoretc/vintf/manifest
mkdir -p /vendoretc/qcril_database
mkdir -p /vendoretc/qcril_database/upgrade
mkdir -p /vendoretc/qcril_database/upgrade/config
mkdir -p /vendoretc/qcril_database/upgrade/other
mkdir -p /vendoretc/configstore
mkdir -p /vendoretc/default-permissions
mkdir -p /vendoretc/acdbdata
mkdir -p /vendoretc/acdbdata/parrot_qrd
mkdir -p /vendoretc/acdbdata/ravelin_idp_wsahac
mkdir -p /vendoretc/acdbdata/IDP_UPD
mkdir -p /vendoretc/acdbdata/parrot_idp_sku1
mkdir -p /vendoretc/acdbdata/ravelin_qrd
mkdir -p /vendoretc/acdbdata/ravelin_idp
mkdir -p /vendoretc/acdbdata/parrot_idp
mkdir -p /vendoretc/acdbdata/parrot_qrd_sku1
mkdir -p /vendoretc/acdbdata/nn_vad_models
mkdir -p /vendoretc/acdbdata/nn_ns_models
mkdir -p /vendoretc/hostapd
mkdir -p /vendoretc/models
mkdir -p /vendoretc/models/acd
mkdir -p /vendoretc/data
mkdir -p /vendoretc/display
mkdir -p /vendoretc/res
mkdir -p /vendoretc/res/SetupWizard
mkdir -p /vendoretc/res/FOTA
mkdir -p /vendoretc/res/GameAssistant
mkdir -p /vendoretc/res/GameAssistant/guide
mkdir -p /vendoretc/res/FactoryTest
mkdir -p /vendoretc/pwr
mkdir -p /vendoretc/audio
mkdir -p /vendoretc/audio/sku_parrot_qssi
mkdir -p /vendoretc/audio/sku_ravelin
mkdir -p /vendoretc/audio/sku_parrot
mkdir -p /vendoretc/audio/sku_ravelin_qssi
mkdir -p /vendoretc/media_parrot_v0
mkdir -p /vendoretc/ssg
mkdir -p /vendoretc/wifi
mkdir -p /vendoretc/wifi/qca6490
mkdir -p /vendoretc/wifi/adrastea
mkdir -p /vendoretc/wifi/qca6750
mkdir -p /vendoretc/media_parrot_v2
mkdir -p /vendoretc/media_parrot_v1
mkdir -p /vendoretc/init
mkdir -p /vendoretc/init/hw
mkdir -p /vendoretc/cne
mkdir -p /vendoretc/cne/wqeclient
mkdir -p /vendoretc/cne/wqeclient/ATT
mkdir -p /vendoretc/cne/wqeclient/VZW
mkdir -p /vendoretc/cne/wqeclient/ROW
mkdir -p /vendoretc/selinux
mkdir -p /vendoretc/perf
mkdir -p /vendoretc/permissions
mkdir -p /vendoretc/permissions/noRil
mkdir -p /vendoretc/permissions/sku_ravelin
mkdir -p /vendoretc/permissions/sku_parrot
mkdir -p /vendoretc/sensors
mkdir -p /vendoretc/sensors/config
mkdir -p /vendoretc/media_ravelin
mkdir -p /vendoretc/dpm_vndr
mkdir -p /vendorlost+found
mkdir -p /vendorbt_firmware
mkdir -p /vendorfirmware
mkdir -p /vendorfirmware/wlan
mkdir -p /vendorfirmware/wlan/qca_cld
mkdir -p /vendorfirmware/wlan/qca_cld/qca6490
mkdir -p /vendorfirmware/wlan/qca_cld/adrastea
mkdir -p /vendorfirmware/wlan/qca_cld/qca6750
mkdir -p /vendorvm-system
mkdir -p /vendorodm_dlkm
mkdir -p /vendorodm_dlkm/etc
mkdir -p /vendorrfs
mkdir -p /vendorrfs/mdm
mkdir -p /vendorrfs/mdm/tn
mkdir -p /vendorrfs/mdm/tn/readonly
mkdir -p /vendorrfs/mdm/tn/readonly/vendor
mkdir -p /vendorrfs/mdm/slpi
mkdir -p /vendorrfs/mdm/slpi/readonly
mkdir -p /vendorrfs/mdm/slpi/readonly/vendor
mkdir -p /vendorrfs/mdm/wpss
mkdir -p /vendorrfs/mdm/wpss/readonly
mkdir -p /vendorrfs/mdm/wpss/readonly/vendor
mkdir -p /vendorrfs/mdm/adsp
mkdir -p /vendorrfs/mdm/adsp/readonly
mkdir -p /vendorrfs/mdm/adsp/readonly/vendor
mkdir -p /vendorrfs/mdm/mpss
mkdir -p /vendorrfs/mdm/mpss/readonly
mkdir -p /vendorrfs/mdm/mpss/readonly/vendor
mkdir -p /vendorrfs/mdm/cdsp
mkdir -p /vendorrfs/mdm/cdsp/readonly
mkdir -p /vendorrfs/mdm/cdsp/readonly/vendor
mkdir -p /vendorrfs/msm
mkdir -p /vendorrfs/msm/slpi
mkdir -p /vendorrfs/msm/slpi/readonly
mkdir -p /vendorrfs/msm/slpi/readonly/vendor
mkdir -p /vendorrfs/msm/wpss
mkdir -p /vendorrfs/msm/wpss/readonly
mkdir -p /vendorrfs/msm/wpss/readonly/vendor
mkdir -p /vendorrfs/msm/adsp
mkdir -p /vendorrfs/msm/adsp/readonly
mkdir -p /vendorrfs/msm/adsp/readonly/vendor
mkdir -p /vendorrfs/msm/mpss
mkdir -p /vendorrfs/msm/mpss/readonly
mkdir -p /vendorrfs/msm/mpss/readonly/vendor
mkdir -p /vendorrfs/msm/cdsp
mkdir -p /vendorrfs/msm/cdsp/readonly
mkdir -p /vendorrfs/msm/cdsp/readonly/vendor
mkdir -p /vendorrfs/apq
mkdir -p /vendorrfs/apq/gnss
mkdir -p /vendorrfs/apq/gnss/readonly
mkdir -p /vendorrfs/apq/gnss/readonly/vendor
mkdir -p /vendorlib
mkdir -p /vendorlib/mediacas
mkdir -p /vendorlib/rfsa
mkdir -p /vendorlib/rfsa/adsp
mkdir -p /vendorlib/vndk
mkdir -p /vendorlib/egl
mkdir -p /vendorlib/soundfx
mkdir -p /vendorlib/hw
mkdir -p /vendorlib/mediadrm
mkdir -p /vendorfirmware_mnt
mkdir -p /vendorbin
mkdir -p /vendorbin/hw
mkdir -p /vendorbin/qmi-framework-tests
mkdir -p /vendorlib64
mkdir -p /vendorlib64/mediacas
mkdir -p /vendorlib64/egl
mkdir -p /vendorlib64/soundfx
mkdir -p /vendorlib64/hw
mkdir -p /vendorlib64/mediadrm
mkdir -p /vendorgpu
mkdir -p /vendorgpu/kbc
mkdir -p /vendoroverlay
mkdir -p /vendordsp
