mkdir -p vendor/app
mkdir -p vendor/app/CACertService
mkdir -p vendor/app/CACertService/oat
mkdir -p vendor/app/CACertService/oat/arm64
mkdir -p vendor/app/CneApp
mkdir -p vendor/app/CneApp/lib
mkdir -p vendor/app/CneApp/lib/arm64
mkdir -p vendor/app/CneApp/oat
mkdir -p vendor/app/CneApp/oat/arm64
mkdir -p vendor/app/ConnectionSecurityService
mkdir -p vendor/app/ConnectionSecurityService/oat
mkdir -p vendor/app/ConnectionSecurityService/oat/arm64
mkdir -p vendor/app/IWlanService
mkdir -p vendor/app/IWlanService/oat
mkdir -p vendor/app/IWlanService/oat/arm64
mkdir -p vendor/app/QFingerprintService
mkdir -p vendor/app/QFingerprintService/oat
mkdir -p vendor/app/QFingerprintService/oat/arm64
mkdir -p vendor/app/TimeService
mkdir -p vendor/app/TimeService/oat
mkdir -p vendor/app/TimeService/oat/arm64
mkdir -p vendor/app/TrustZoneAccessService
mkdir -p vendor/app/TrustZoneAccessService/oat
mkdir -p vendor/app/TrustZoneAccessService/oat/arm64
mkdir -p vendor/app/TrustedUIService
mkdir -p vendor/app/TrustedUIService/oat
mkdir -p vendor/app/TrustedUIService/oat/arm64
mkdir -p vendor/app/TxPwrAdmin
mkdir -p vendor/app/TxPwrAdmin/oat
mkdir -p vendor/app/TxPwrAdmin/oat/arm64
mkdir -p vendor/app/com.qualcomm.qti.gpudrivers.kalama.api33
mkdir -p vendor/app/pasrservice
mkdir -p vendor/app/pasrservice/oat
mkdir -p vendor/app/pasrservice/oat/arm64
mkdir -p vendor/bin
mkdir -p vendor/bin/hw
mkdir -p vendor/bin/qmi-framework-tests
mkdir -p vendor/bt_firmware
mkdir -p vendor/dsp
mkdir -p vendor/etc
mkdir -p vendor/etc/acdbdata
mkdir -p vendor/etc/acdbdata/IDP_UPD
mkdir -p vendor/etc/acdbdata/ffv_models
mkdir -p vendor/etc/acdbdata/kalama_cdp
mkdir -p vendor/etc/acdbdata/kalama_cdp_apq
mkdir -p vendor/etc/acdbdata/kalama_grd
mkdir -p vendor/etc/acdbdata/kalama_mtp
mkdir -p vendor/etc/acdbdata/kalama_mtp_apq
mkdir -p vendor/etc/acdbdata/kalama_qrd
mkdir -p vendor/etc/acdbdata/nn_ns_models
mkdir -p vendor/etc/acdbdata/nn_vad_models
mkdir -p vendor/etc/audio
mkdir -p vendor/etc/audio/sku_kalama
mkdir -p vendor/etc/audio/sku_kalama_qssi
mkdir -p vendor/etc/cne
mkdir -p vendor/etc/cne/wqeclient
mkdir -p vendor/etc/cne/wqeclient/ATT
mkdir -p vendor/etc/cne/wqeclient/ROW
mkdir -p vendor/etc/cne/wqeclient/VZW
mkdir -p vendor/etc/configstore
mkdir -p vendor/etc/data
mkdir -p vendor/etc/default-permissions
mkdir -p vendor/etc/display
mkdir -p vendor/etc/dpm_vndr
mkdir -p vendor/etc/eva
mkdir -p vendor/etc/eva/facedetection
mkdir -p vendor/etc/hostapd
mkdir -p vendor/etc/init
mkdir -p vendor/etc/init/hw
mkdir -p vendor/etc/lm
mkdir -p vendor/etc/lm/prekill
mkdir -p vendor/etc/media_kalama
mkdir -p vendor/etc/media_kalama_iot
mkdir -p vendor/etc/media_kalama_iot_v1
mkdir -p vendor/etc/models
mkdir -p vendor/etc/models/acd
mkdir -p vendor/etc/perf
mkdir -p vendor/etc/permissions
mkdir -p vendor/etc/permissions/noRil
mkdir -p vendor/etc/permissions/sku_kalama
mkdir -p vendor/etc/pwr
mkdir -p vendor/etc/qcril_database
mkdir -p vendor/etc/qcril_database/upgrade
mkdir -p vendor/etc/qcril_database/upgrade/config
mkdir -p vendor/etc/qcril_database/upgrade/other
mkdir -p vendor/etc/qvr
mkdir -p vendor/etc/qvr/cfg
mkdir -p vendor/etc/qvr/cfg/519
mkdir -p vendor/etc/qvr/cfg/519/0
mkdir -p vendor/etc/qvr/cfg/519/0/65536
mkdir -p vendor/etc/res
mkdir -p vendor/etc/res/FactoryTest
mkdir -p vendor/etc/res/GameAssistant
mkdir -p vendor/etc/res/GameAssistant/guide
mkdir -p vendor/etc/res/SetupWizard
mkdir -p vendor/etc/res/images
mkdir -p vendor/etc/res/images/default
mkdir -p vendor/etc/res/images/default/charger
mkdir -p vendor/etc/seccomp_policy
mkdir -p vendor/etc/selinux
mkdir -p vendor/etc/sensors
mkdir -p vendor/etc/sensors/config
mkdir -p vendor/etc/ssg
mkdir -p vendor/etc/thermal_config
mkdir -p vendor/etc/vintf
mkdir -p vendor/etc/vintf/manifest
mkdir -p vendor/etc/wifi
mkdir -p vendor/etc/wifi/kiwi
mkdir -p vendor/etc/wifi/kiwi_v2
mkdir -p vendor/etc/wifi/qca6490
mkdir -p vendor/firmware
mkdir -p vendor/firmware/wlan
mkdir -p vendor/firmware/wlan/qca_cld
mkdir -p vendor/firmware/wlan/qca_cld/kiwi
mkdir -p vendor/firmware/wlan/qca_cld/kiwi_v2
mkdir -p vendor/firmware/wlan/qca_cld/qca6490
mkdir -p vendor/firmware_mnt
mkdir -p vendor/gpu
mkdir -p vendor/gpu/kbc
mkdir -p vendor/lib
mkdir -p vendor/lib/camera
mkdir -p vendor/lib/camera/components
mkdir -p vendor/lib/egl
mkdir -p vendor/lib/hw
mkdir -p vendor/lib/mediacas
mkdir -p vendor/lib/mediadrm
mkdir -p vendor/lib/rfsa
mkdir -p vendor/lib/rfsa/adsp
mkdir -p vendor/lib/soundfx
mkdir -p vendor/lib/vndk
mkdir -p vendor/lib64
mkdir -p vendor/lib64/camera
mkdir -p vendor/lib64/camera/components
mkdir -p vendor/lib64/egl
mkdir -p vendor/lib64/hw
mkdir -p vendor/lib64/mediacas
mkdir -p vendor/lib64/mediadrm
mkdir -p vendor/lib64/soundfx
mkdir -p vendor/lost+found
mkdir -p vendor/odm_dlkm
mkdir -p vendor/odm_dlkm/etc
mkdir -p vendor/overlay
mkdir -p vendor/preinstall
mkdir -p vendor/preinstall/apk
mkdir -p vendor/rfs
mkdir -p vendor/rfs/apq
mkdir -p vendor/rfs/apq/gnss
mkdir -p vendor/rfs/apq/gnss/readonly
mkdir -p vendor/rfs/apq/gnss/readonly/vendor
mkdir -p vendor/rfs/mdm
mkdir -p vendor/rfs/mdm/adsp
mkdir -p vendor/rfs/mdm/adsp/readonly
mkdir -p vendor/rfs/mdm/adsp/readonly/vendor
mkdir -p vendor/rfs/mdm/cdsp
mkdir -p vendor/rfs/mdm/cdsp/readonly
mkdir -p vendor/rfs/mdm/cdsp/readonly/vendor
mkdir -p vendor/rfs/mdm/mpss
mkdir -p vendor/rfs/mdm/mpss/readonly
mkdir -p vendor/rfs/mdm/mpss/readonly/vendor
mkdir -p vendor/rfs/mdm/slpi
mkdir -p vendor/rfs/mdm/slpi/readonly
mkdir -p vendor/rfs/mdm/slpi/readonly/vendor
mkdir -p vendor/rfs/mdm/tn
mkdir -p vendor/rfs/mdm/tn/readonly
mkdir -p vendor/rfs/mdm/tn/readonly/vendor
mkdir -p vendor/rfs/mdm/wpss
mkdir -p vendor/rfs/mdm/wpss/readonly
mkdir -p vendor/rfs/mdm/wpss/readonly/vendor
mkdir -p vendor/rfs/msm
mkdir -p vendor/rfs/msm/adsp
mkdir -p vendor/rfs/msm/adsp/readonly
mkdir -p vendor/rfs/msm/adsp/readonly/vendor
mkdir -p vendor/rfs/msm/cdsp
mkdir -p vendor/rfs/msm/cdsp/readonly
mkdir -p vendor/rfs/msm/cdsp/readonly/vendor
mkdir -p vendor/rfs/msm/mpss
mkdir -p vendor/rfs/msm/mpss/readonly
mkdir -p vendor/rfs/msm/mpss/readonly/vendor
mkdir -p vendor/rfs/msm/slpi
mkdir -p vendor/rfs/msm/slpi/readonly
mkdir -p vendor/rfs/msm/slpi/readonly/vendor
mkdir -p vendor/rfs/msm/wpss
mkdir -p vendor/rfs/msm/wpss/readonly
mkdir -p vendor/rfs/msm/wpss/readonly/vendor
mkdir -p vendor/vm-system
