mkdir -p vendor/app
mkdir -p vendor/app/CneApp
mkdir -p vendor/app/CneApp/lib
mkdir -p vendor/app/CneApp/lib/arm64
mkdir -p vendor/app/TimeService
mkdir -p vendor/app/TimeService/oat
mkdir -p vendor/app/TimeService/oat/arm64
mkdir -p vendor/app/CACertService
mkdir -p vendor/app/CACertService/oat
mkdir -p vendor/app/CACertService/oat/arm64
mkdir -p vendor/app/QCC-TR-UI
mkdir -p vendor/app/QCC-TR-UI/oat
mkdir -p vendor/app/QCC-TR-UI/oat/arm64
mkdir -p vendor/etc
mkdir -p vendor/etc/seccomp_policy
mkdir -p vendor/etc/lm
mkdir -p vendor/etc/lm/prekill
mkdir -p vendor/etc/vintf
mkdir -p vendor/etc/vintf/manifest
mkdir -p vendor/etc/qcril_database
mkdir -p vendor/etc/qcril_database/upgrade
mkdir -p vendor/etc/qcril_database/upgrade/config
mkdir -p vendor/etc/qcril_database/upgrade/other
mkdir -p vendor/etc/media_khaje_iot
mkdir -p vendor/etc/configstore
mkdir -p vendor/etc/default-permissions
mkdir -p vendor/etc/acdbdata
mkdir -p vendor/etc/acdbdata/bengal_idp
mkdir -p vendor/etc/acdbdata/bengal_qrd_arrax
mkdir -p vendor/etc/acdbdata/bengal_scubaidp
mkdir -p vendor/etc/acdbdata/bengal_idp_arrax
mkdir -p vendor/etc/acdbdata/bengal_scubaqrd
mkdir -p vendor/etc/acdbdata/bengal_qrd
mkdir -p vendor/etc/acdbdata/nn_vad_models
mkdir -p vendor/etc/acdbdata/nn_ns_models
mkdir -p vendor/etc/hostapd
mkdir -p vendor/etc/media_bengal_v1
mkdir -p vendor/etc/data
mkdir -p vendor/etc/display
mkdir -p vendor/etc/res
mkdir -p vendor/etc/res/images
mkdir -p vendor/etc/res/images/default
mkdir -p vendor/etc/res/images/default/charger
mkdir -p vendor/etc/audio
mkdir -p vendor/etc/ssg
mkdir -p vendor/etc/wifi
mkdir -p vendor/etc/tlog
mkdir -p vendor/etc/init
mkdir -p vendor/etc/init/hw
mkdir -p vendor/etc/cne
mkdir -p vendor/etc/cne/wqeclient
mkdir -p vendor/etc/cne/wqeclient/ATT
mkdir -p vendor/etc/cne/wqeclient/VZW
mkdir -p vendor/etc/cne/wqeclient/ROW
mkdir -p vendor/etc/selinux
mkdir -p vendor/etc/perf
mkdir -p vendor/etc/permissions
mkdir -p vendor/etc/permissions/noRil
mkdir -p vendor/etc/sensors
mkdir -p vendor/etc/sensors/config
mkdir -p vendor/etc/media_khaje_v0
mkdir -p vendor/etc/dpm_vndr
mkdir -p vendor/lost+found
mkdir -p vendor/bt_firmware
mkdir -p vendor/firmware
mkdir -p vendor/firmware/wlan
mkdir -p vendor/firmware/wlan/qca_cld
mkdir -p vendor/odm_dlkm
mkdir -p vendor/odm_dlkm/etc
mkdir -p vendor/rfs
mkdir -p vendor/rfs/mdm
mkdir -p vendor/rfs/mdm/tn
mkdir -p vendor/rfs/mdm/tn/readonly
mkdir -p vendor/rfs/mdm/tn/readonly/vendor
mkdir -p vendor/rfs/mdm/slpi
mkdir -p vendor/rfs/mdm/slpi/readonly
mkdir -p vendor/rfs/mdm/slpi/readonly/vendor
mkdir -p vendor/rfs/mdm/wpss
mkdir -p vendor/rfs/mdm/wpss/readonly
mkdir -p vendor/rfs/mdm/wpss/readonly/vendor
mkdir -p vendor/rfs/mdm/adsp
mkdir -p vendor/rfs/mdm/adsp/readonly
mkdir -p vendor/rfs/mdm/adsp/readonly/vendor
mkdir -p vendor/rfs/mdm/mpss
mkdir -p vendor/rfs/mdm/mpss/readonly
mkdir -p vendor/rfs/mdm/mpss/readonly/vendor
mkdir -p vendor/rfs/mdm/cdsp
mkdir -p vendor/rfs/mdm/cdsp/readonly
mkdir -p vendor/rfs/mdm/cdsp/readonly/vendor
mkdir -p vendor/rfs/msm
mkdir -p vendor/rfs/msm/slpi
mkdir -p vendor/rfs/msm/slpi/readonly
mkdir -p vendor/rfs/msm/slpi/readonly/vendor
mkdir -p vendor/rfs/msm/wpss
mkdir -p vendor/rfs/msm/wpss/readonly
mkdir -p vendor/rfs/msm/wpss/readonly/vendor
mkdir -p vendor/rfs/msm/adsp
mkdir -p vendor/rfs/msm/adsp/readonly
mkdir -p vendor/rfs/msm/adsp/readonly/vendor
mkdir -p vendor/rfs/msm/mpss
mkdir -p vendor/rfs/msm/mpss/readonly
mkdir -p vendor/rfs/msm/mpss/readonly/vendor
mkdir -p vendor/rfs/msm/cdsp
mkdir -p vendor/rfs/msm/cdsp/readonly
mkdir -p vendor/rfs/msm/cdsp/readonly/vendor
mkdir -p vendor/rfs/apq
mkdir -p vendor/rfs/apq/gnss
mkdir -p vendor/rfs/apq/gnss/readonly
mkdir -p vendor/rfs/apq/gnss/readonly/vendor
mkdir -p vendor/lib
mkdir -p vendor/lib/mediacas
mkdir -p vendor/lib/rfsa
mkdir -p vendor/lib/rfsa/adsp
mkdir -p vendor/lib/vndk
mkdir -p vendor/lib/egl
mkdir -p vendor/lib/camera
mkdir -p vendor/lib/camera/components
mkdir -p vendor/lib/soundfx
mkdir -p vendor/lib/hw
mkdir -p vendor/lib/mediadrm
mkdir -p vendor/firmware_mnt
mkdir -p vendor/bin
mkdir -p vendor/bin/hw
mkdir -p vendor/bin/qmi-framework-tests
mkdir -p vendor/lib64
mkdir -p vendor/lib64/mediacas
mkdir -p vendor/lib64/rfsa
mkdir -p vendor/lib64/rfsa/adsp
mkdir -p vendor/lib64/egl
mkdir -p vendor/lib64/camera
mkdir -p vendor/lib64/camera/components
mkdir -p vendor/lib64/soundfx
mkdir -p vendor/lib64/hw
mkdir -p vendor/lib64/mediadrm
mkdir -p vendor/gpu
mkdir -p vendor/gpu/kbc
mkdir -p vendor/overlay
mkdir -p vendor/dsp

rm -f vendor.img
MKE2FS_CONFIG=mke2fs.conf ./mke2fs -O ^has_journal,^sparse_super -L vendor -M /vendor -m 0 -t ext4 -b 4096 vendor.img 200000
./e2fsdroid -e -T 1230768000 -S selinux_contexts.txt -f vendor/ -a / vendor.img
